Sprint 11
DeVIn4I/ImageFeed pull request #4
Opened 2023-02-07 19:56 UTC by DeVIn4I

2023-02-08 20:34 UTC, IBDesignable requested changes

2023-02-08 20:34 UTC, IBDesignable commented on ImageFeed/Auth/WebViewViewController.swift
> +
А почему убрал сюда?

Было же правильно: подписка-оптиска в соответствюущих методах

2023-02-08 20:34 UTC, IBDesignable commented on ImageFeed/Extensions/URLRequest.swift
> +
```suggestion
            baseURL: URL = defaultBaseURL,
            token: String? = nil
```

2023-02-08 20:34 UTC, IBDesignable commented on ImageFeed/Extensions/URLRequest.swift
> +        enum HTTPMethod: String { case GET, POST, DELETE, PUT }
вообще не принято кейсы енумов не в camelCase писать, но тут даже не знаю :) 

В качестве исключения для этого случая может и хорошо именно так писать)

2023-02-08 20:34 UTC, IBDesignable commented on ImageFeed/Extensions/URLRequest.swift
> +            var request = URLRequest(url: URL(string: path, relativeTo: baseURL)!)
Когда ты собираешь ссылку из понятной строки, ктороая точно всегда окажется ссылкой (например "https://ya.ru"), уместно делать force unwrap, но здесь не так – в path  может оказаться что угодно и приложение будет падать. 

Я не рекомендую писать общедоступный экстеншен с небезопасным кодом. 

Вот если это была бы фабрика/билдер, который будет собирать реквест из ограниченного числа таких строк (например описать все path в enum AppRoute: String { case me = "/me" }), то другое дело – так ты как бы и форс анврапишь, но "мамойклянусь все будет работать")

2023-02-08 20:34 UTC, IBDesignable commented on ImageFeed/OAuth2/OAuth2Service.swift
>              }
после свитча можно и таску обнулить, и код сбросить. Разве нет?

2023-02-08 20:34 UTC, IBDesignable commented on ImageFeed/OAuth2/OAuth2Service.swift
> +            baseURL: URL(string: "https://unsplash.com")!
Где-то кажется уже рассказывали что для таких URL лучше использовать URLComponents

2023-02-08 20:34 UTC, IBDesignable commented on ImageFeed/OAuth2/OAuth2Service.swift
> +
```suggestion
```

2023-02-08 20:34 UTC, IBDesignable commented on ImageFeed/OAuth2/OAuth2TokenStorage.swift
> +        }
👍🏻

2023-02-08 20:34 UTC, IBDesignable commented on ImageFeed/Profile/ProfileImageService.swift
> +    static let DidChangeNotification = Notification.Name("ProfileImageProviderDidChange")
Рекомендую для констант использовать общепринятый codestyle в нижнем camelCase

2023-02-08 20:34 UTC, IBDesignable commented on ImageFeed/Profile/ProfileImageService.swift
> +        let request = URLRequest.makeHTTPRequest(path: "users/\(username)", token: OAuth2TokenStorage().token)
давай OAuth2TokenStorage() сложим как зависимость этого сервиса

2023-02-08 20:34 UTC, IBDesignable commented on ImageFeed/Profile/ProfileViewController.swift
> +        profileImageServiceObserver = NotificationCenter.default
рекомендую подписываться и отписываться в двух методах didApper-didDissapear, и придерживаться этого правила всегда. 

Этот код взаимодействует с UI, и планирует его обновать – нет смысла выполнять операции, если экран не отображен или скрыт чем-то другим.

2023-02-08 20:34 UTC, IBDesignable commented on ImageFeed/Profile/ProfileViewController.swift
> +        loginNameLabel.text = profile?.loginName ?? "1"
тут лучше уж тогда ничего не писать, либо делать плейсхолдеры "Your name", "@"

2023-02-08 20:34 UTC, IBDesignable commented on ImageFeed/Profile/ProfileViewController.swift
>      func setupUI() {
У этого экрана теперь фон не соответствует макетам 
<img width="380" alt="Снимок экрана 2023-02-08 в 22 04 29" src="https://user-images.githubusercontent.com/121577115/217643665-4b0d8497-d3d9-437c-b265-09597345bfea.png">

2023-02-08 20:34 UTC, IBDesignable commented on ImageFeed/SplashViewController/SplashViewController.swift
> +                print(error.localizedDescription)
Здесь тоже надо показать ошибку

А перед этим скрыть UIBlockingProgressHUD.
Чтобы с ним не повторяться, можно дисмисить немного раньше – перед свитчом

2023-02-08 20:34 UTC, IBDesignable commented on ImageFeed/SplashViewController/SplashViewController.swift
> +                UIBlockingProgressHUD.dismiss()
обычно сначала прячут пропеллер, затем показывают новый контекст. Давай поменяем местами

2023-02-08 20:34 UTC, IBDesignable commented on ImageFeed/TabBarController.swift
> +            selectedImage: nil)
обрати внимание, что в макетах подписи к табам не нужны. 

Похоже на опечатку из учебника. Давай поправим?

2023-02-09 05:48 UTC, DeVIn4I commented on ImageFeed/Auth/WebViewViewController.swift
> +
Поправил. Но в практикуме не нашел правило про подписку в соответствующих методах.
<img width="834" alt="image" src="https://user-images.githubusercontent.com/79083903/217728934-b6fcc502-0f44-4cff-9b9a-b728c6824bbf.png">

2023-02-09 18:55 UTC, IBDesignable commented on ImageFeed/Auth/WebViewViewController.swift
> +
Не уверена что ссылка на урок откроется, [10 спринт, KVO](https://practicum.yandex.ru/learn/ios-developer/courses/6aebbc23-2480-4618-9999-3a7555e7156c/sprints/79799/topics/76fa8540-e095-4db9-9a57-6c3110e8efc7/lessons/3a00a310-ad04-4cf4-adba-8cc6282f0176/)
<img width="465" alt="Снимок экрана 2023-02-09 в 20 54 42" src="https://user-images.githubusercontent.com/121577115/217910091-b6fefac8-e573-4f24-a175-814946c1f33d.png">
<img width="610" alt="Снимок экрана 2023-02-09 в 20 54 39" src="https://user-images.githubusercontent.com/121577115/217910101-f0641ecb-f297-4b9c-b4c7-1d6171721e59.png">

2023-02-09 18:57 UTC, IBDesignable commented on ImageFeed/OAuth2/OAuth2Service.swift
> +                self?.lastCode = nil
а в случае failure обнулить task?

2023-02-09 18:58 UTC, IBDesignable approved these changes

2023-02-12 16:45 UTC, merged